basePath: /
definitions:
  domain.Booking:
    properties:
      addons:
        items:
          $ref: '#/definitions/domain.BookingAddon'
        type: array
      check_in_date:
        type: string
      check_out_date:
        type: string
      created_at:
        type: string
      expires_at:
        type: string
      grand_total:
        type: number
      guest_id:
        type: string
      id:
        type: string
      receipt_number:
        type: string
      room_id:
        type: string
      status:
        type: string
      total_addons_price:
        type: number
      total_room_price:
        type: number
    type: object
  domain.BookingAddon:
    properties:
      addon_id:
        type: string
      booking_id:
        type: string
      id:
        type: string
      price_at_booking:
        type: number
      quantity:
        type: integer
    type: object
  domain.CreateBookingRequest:
    properties:
      check_in_date:
        description: format YYYY-MM-DD
        type: string
      check_out_date:
        description: format YYYY-MM-DD
        type: string
      guest_id:
        type: string
      room_id:
        type: string
    required:
    - check_in_date
    - check_out_date
    - guest_id
    - room_id
    type: object
  domain.ErrorResponse:
    properties:
      errors:
        description: 'Opsional: Detail error validasi'
      message:
        description: Detail pesan kesalahan
        type: string
      status:
        description: Biasanya diisi "error" atau "fail"
        type: string
    type: object
  domain.Meta:
    properties:
      api_version:
        type: string
      service_name:
        type: string
    type: object
  domain.SuccessResponse:
    properties:
      data:
        description: Objek atau Array data utama
      message:
        description: Pesan sukses
        type: string
      meta:
        allOf:
        - $ref: '#/definitions/domain.Meta'
        description: Informasi tambahan (opsional)
      status:
        description: Biasanya diisi "success"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API untuk layanan reservasi booking hotel (IAE Tubes)
  title: Layanan Reservasi API
  version: "1.0"
paths:
  /api/v1/bookings:
    get:
      description: Mendapatkan daftar seluruh reservasi (kebutuhan kontrak API)
      parameters:
      - description: API Key
        in: header
        name: X-IAE-KEY
        required: true
        type: string
      - description: Bearer JWT Token dari SSO
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/domain.SuccessResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/domain.Booking'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Mengambil semua pesanan (Collection)
      tags:
      - Bookings
    post:
      consumes:
      - application/json
      description: Endpoint untuk membuat reservasi awal dengan status LOCKED. Terintegrasi
        dengan SOAP Audit dan Message Broker.
      parameters:
      - description: API Key
        in: header
        name: X-IAE-KEY
        required: true
        type: string
      - description: Bearer JWT Token dari SSO
        in: header
        name: Authorization
        required: true
        type: string
      - description: Kunci unik untuk mencegah duplikasi request
        in: header
        name: Idempotency-Key
        type: string
      - description: Payload Reservasi
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.CreateBookingRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/domain.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/domain.Booking'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Membuat pesanan awal (mengunci kamar)
      tags:
      - Bookings
  /api/v1/bookings/{id}:
    get:
      description: Mendapatkan rincian spesifik satu reservasi berdasarkan ID
      parameters:
      - description: API Key
        in: header
        name: X-IAE-KEY
        required: true
        type: string
      - description: Bearer JWT Token dari SSO
        in: header
        name: Authorization
        required: true
        type: string
      - description: Booking ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/domain.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/domain.Booking'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Mengambil detail pesanan (Resource)
      tags:
      - Bookings
swagger: "2.0"
